swagger: '2.0'
info:
  version: '1.0.0-beta'
  title: Analytics Edits Metrics API
  description: Analytics Edits Metrics API
  termsofservice: https://github.com/wikimedia/restbase#restbase
  contact:
    name: Analytics
    email: analytics@lists.wikimedia.org
    url: https://www.mediawiki.org/wiki/Analytics
  license:
    name: Apache licence, v2
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /:
    get:
      tags:
        - Edits data
      summary: List mediawiki edits metrics related API entry points.
      description: |
        This is the root of mediawiki edits metrics data endpoints. If browsing the interactive
        documentation, see the specifics for each endpoint below.

        Stability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Stable)
      produces:
        - application/json
      responses:
        '200':
          description: The queriable sub-items
          schema:
            $ref: '#/definitions/listing'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-monitor: false

  /aggregate/{project}/{editor-type}/{page-type}/{granularity}/{start}/{end}:
    get:
      tags:
        - Edits data
      summary: Get edits counts.
      description: |
        Given a Mediawiki project and a date range, returns a timeseries of edits counts. You can
        filter by editors-type (all-editor-types, anonymous, group-bot, name-bot, user) and
        page-type (all-page-types, content or non-content). You can choose between daily and
        monthly granularity as well.
        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)
      produces:
        - application/json
      parameters:
        - name: project
          in: path
          description: |
            The name of any Wikimedia project formatted like {language code}.{project name},
            for example en.wikipedia. You may pass en.wikipedia.org and the .org will be stripped
            off. For projects like commons without language codes, use commons.wikimedia. For
            projects like www.mediawiki.org, you can use that full string, or just use mediawiki
            or mediawiki.org. If you're interested in the aggregation of all projects or
            project-families, use all-projects or all-[family]-projects (i.e.
            all-wikipedia-projects for instance).
          type: string
          required: true
        - name: editor-type
          in: path
          description: |
            If you want to filter by editor-type, use one of anonymous, group-bot (registered
            accounts belonging to the bot group), name-bot (registered accounts not belonging to
            the bot group but having bot-like names) or user (registered account not in bot group
            nor having bot-like name). If you are interested in edits regardless of their
            editor-type, use all-editor-types.
          type: string
          enum: ['all-editor-types', 'anonymous', 'group-bot', 'name-bot', 'user']
          required: true
        - name: page-type
          in: path
          description: |
            If you want to filter by page-type, use one of content (edits on pages in content
            namespaces) or non-content (edits on pages in non-content namespaces). If you are
            interested in edits regardless of their page-type, use all-page-types.
          type: string
          enum: ['all-page-types', 'content', 'non-content']
          required: true
        - name: granularity
          in: path
          description: |
            Time unit for the response data. As of today, supported values are daily and monthly
          type: string
          enum: ['daily', 'monthly']
          required: true
        - name: start
          in: path
          description: The date of the first day to include, in YYYYMMDD format
          type: string
          required: true
        - name: end
          in: path
          description: The date of the last day to include, in YYYYMMDD format
          type: string
          required: true
      responses:
        '200':
          description: The list of values
          schema:
            $ref: '#/definitions/edits'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: /{domain}/sys/mediawiki-history-metrics/revisions/aggregate/edits/{project}/{editor-type}/{page-type}/{granularity}/{start}/{end}
      x-monitor: false

  /per-page/{project}/{page-title}/{editor-type}/{granularity}/{start}/{end}:
    get:
      tags:
        - Edits data
      summary: Get edit counts for a page in a project.
      description: |
        Given a Mediawiki project, a page-title prefixed with its canonical namespace (for
        instance 'User:Jimbo_Wales')and a date range, returns a timeseries of edit counts.
        You can filter by editors-type (all-editor-types, anonymous, group-bot, name-bot, user).
        You can choose between daily and monthly granularity as well.
        Note: Due to performance of the data-serving backend, this endpoint limits the queryable
        timespan to one year (whether in daily or monthly granularity).
        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)
      produces:
        - application/json
      parameters:
        - name: project
          in: path
          description: |
            The name of any Wikimedia project formatted like {language code}.{project name},
            for example en.wikipedia. You may pass en.wikipedia.org and the .org will be stripped
            off. For projects like commons without language codes, use commons.wikimedia. For
            projects like www.mediawiki.org, you can use that full string, or just use mediawiki
            or mediawiki.org. If you are interested in the aggregation of all projects or
            project-families, use all-projects or all-[family]-projects (i.e.
            all-wikipedia-projects for instance).
          type: string
          required: true
        - name: page-title
          in: path
          description: |
            The page-title to request edits for. It should be prefixed with canonical namespace.
            Spaces will be converted to underscores.
          type: string
          required: true
        - name: editor-type
          in: path
          description: |
            If you want to filter by editor-type, use one of anonymous, group-bot (registered
            accounts belonging to the bot group), name-bot (registered accounts not belonging to
            the bot group but having bot-like names) or user (registered account not in bot group
            nor having bot-like name). If you are interested in edits regardless of their
            editor-type, use all-editor-types.
          type: string
          enum: ['all-editor-types', 'anonymous', 'group-bot', 'name-bot', 'user']
          required: true
        - name: granularity
          in: path
          description: |
            Time unit for the response data. As of today, supported values are daily and monthly
          type: string
          enum: ['daily', 'monthly']
          required: true
        - name: start
          in: path
          description: The date of the first day to include, in YYYYMMDD format
          type: string
          required: true
        - name: end
          in: path
          description: The date of the last day to include, in YYYYMMDD format
          type: string
          required: true
      responses:
        '200':
          description: The list of values
          schema:
            $ref: '#/definitions/edits-per-page'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: /{domain}/sys/mediawiki-history-metrics/revisions/per-page/edits/{project}/{page-title}/{editor-type}/{granularity}/{start}/{end}
      # This endpoint is used to monitor druid bein set
      # (correct datasource and expected schema for this endpoint)
      x-monitor: true
      x-amples:
        - title: Get daily edits for english wikipedia page 0
          request:
            params:
              domain: wikimedia.org
              project: en.wikipedia
              page-title: Main_page
              editor-type: all-editor-types
              granularity: daily
              start: 20010101
              end: 20010102
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              items:
                - project: en.wikipedia
                  page-title: Main_page
                  editor-type: all-editor-types
                  granularity: daily
                  results:
                    - timestamp: 2001-01-01T00:00:00.000Z
                      edits: 0

  /per-editor/{project}/{user-text}/{page-type}/{granularity}/{start}/{end}:
    get:
      tags:
        - Edits data
      summary: Get the edits counts for an editor in a project.
      description: |
        Given a Mediawiki project, a user-text and a date range, returns a timeseries of edits
        counts. You can filter by page type (all-page-types, content or non-content). You can
        choose between daily and monthly granularity as well.
        Note: Due to performance of the data-serving backend, this endpoint limits the queryable
        timespan to one year (whether in daily or monthly granularity).
        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)
      produces:
        - application/json
      parameters:
        - name: project
          in: path
          description: |
            The name of any Wikimedia project formatted like {language code}.{project name},
            for example en.wikipedia. You may pass en.wikipedia.org and the .org will be stripped
            off. For projects like commons without language codes, use commons.wikimedia. For
            projects like www.mediawiki.org, you can use that full string, or just use mediawiki
            or mediawiki.org. If you are interested in the aggregation of all projects or
            project-families, use all-projects or all-[family]-projects (i.e.
            all-wikipedia-projects for instance).
          type: string
          required: true
        - name: user-text
          in: path
          description: |
            The user you want to get edits for. Can be either a registered user-name, or an
            anonymous user IP.
          type: string
          required: true
        - name: page-type
          in: path
          description: |
            If you want to filter by page-type, use one of content (edits on pages in content
            namespaces) or non-content (edits on pages in non-content namespaces). If you are
            interested in edits regardless of their page-type, use all-page-types.
          type: string
          enum: ['all-page-types', 'content', 'non-content']
          required: true
        - name: granularity
          in: path
          description: |
            Time unit for the response data. As of today, supported values are daily and monthly
          type: string
          enum: ['daily', 'monthly']
          required: true
        - name: start
          in: path
          description: The date of the first day to include, in YYYYMMDD format
          type: string
          required: true
        - name: end
          in: path
          description: The date of the last day to include, in YYYYMMDD format
          type: string
          required: true
      responses:
        '200':
          description: The list of values
          schema:
            $ref: '#/definitions/edits-per-editor'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: /{domain}/sys/mediawiki-history-metrics/revisions/per-editor/edits/{project}/{user-text}/{page-type}/{granularity}/{start}/{end}
      x-monitor: false

definitions:
  # A https://tools.ietf.org/html/draft-nottingham-http-problem
  problem:
    required:
      - type
    properties:
      type:
        type: string
      title:
        type: string
      detail:
        type: string
      instance:
        type: string

  listing:
    description: The result format for listings
    required:
      - items
    properties:
      items:
        type: array
        items:
          type: string

  edits:
    properties:
      items:
        type: array
        items:
          properties:
            project:
              type : string
            editor-type:
              type : string
            page-type:
              type: string
            granularity:
              type: string
            results:
              type: array
              items:
                properties:
                  timestamp:
                    type: string
                  edits:
                    type: integer
                    format: int64

  edits-per-page:
    properties:
      items:
        type: array
        items:
          properties:
            project:
              type : string
            page-title:
              type: string
            editor-type:
              type : string
            granularity:
              type: string
            results:
              type: array
              items:
                properties:
                  timestamp:
                    type: string
                  edits:
                    type: integer
                    format: int64

  edits-per-editor:
    properties:
      items:
        type: array
        items:
          properties:
            project:
              type : string
            user-text:
              type: string
            page-type:
              type: string
            granularity:
              type: string
            results:
              type: array
              items:
                properties:
                  timestamp:
                    type: string
                  edits:
                    type: integer
                    format: int64
