swagger: '2.0'
info:
  version: '1.0.0-beta'
  title: Test
  description: Test
  termsofservice: https://github.com/wikimedia/restbase#restbase
  contact:
    name: Test
    email: analytics@lists.wikimedia.org
    url: https://www.mediawiki.org/wiki/Analytics
  license:
    name: Apache licence, v2
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /per-category/{project}/{content_gap}/{category}/{start}/{end}:
    get:
      tags:
        - Content gap by category data
      summary: Get content gap data for a category with given metrics
      description: |
        Given a Mediawiki project, content gap, category and date range, returns
        a series of metrics and their values. These metrics are:
        article_count, pageviews_mean, pageviews_sum, quality_score, standard_quality, standard_quality_count.
        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)

        Link to documentation: [click here](https://meta.wikimedia.org/wiki/Research:Knowledge_Gaps_Index/API)
      produces:
        - application/json
      parameters:
        - name: project
          in: path
          description: |
            The name of any Wikimedia project formatted like {language code}.{project name},
            for example en.wikipedia. You may pass en.wikipedia.org and the .org will be stripped
            off. For projects like commons without language codes, use commons.wikimedia. For
            projects like www.mediawiki.org, use mediawiki or mediawiki.org.
          type: string
          required: true
        - name: content_gap
          in: path
          description: |
            The content gap super catergory.
            These categories are:
            gender, time, multimedia_illustration, geography_cultural_region,...
            geography_wmf_region, geography_continent, geography_country
          type: string
          # enum: ["fill in content gaps"]
          required: true
        - name: category
          in: path
          description: |
            Specific category within content gap data to filter for.
            For example, categories in the geography_cultural_region are actual country names...
            like Madagascar, Sweden etc. For time: 14th century, 21st century etc
          type: string
          required: true
        - name: start
          in: path
          description: Date to begin data retrieval. Has the format YYYYMM01
          type: string
          required: true
        - name: end
          in: path
          description: Date to end data retrieval. Has the format YYYYMM01
          type: string
          required: true
      responses:
        '200':
          description: The content gap data for a given category
          schema:
            $ref: '#/definitions/knowledge-gap'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: /{domain}/sys/knowledge-gap/per-category/{project}/{content_gap}/{category}/{start}/{end}
      x-monitor: false

definitions:
  # A https://tools.ietf.org/html/draft-nottingham-http-problem
  problem:
    required:
      - type
    properties:
      type:
        type: string
      title:
        type: string
      detail:
        type: string
      instance:
        type: string

  listing:
    description: The result format for listings
    required:
      - items
    properties:
      items:
        type: array
        items:
          type: string
  
  knowledge-gap:
    properties:
      items:
        type: array
        items:
          properties:
            project:
              type: string
            content_gap:
              type: string
            category:
              type: string
            metric:
              type: string
            value:
              type: number
              format: double