swagger: '2.0'
info:
  version: '1.0.0-beta'
  title: Analytics Mediarequests API
  description: Analytics Mediarequests API
  termsofservice: https://github.com/wikimedia/restbase#restbase
  contact:
    name: Analytics
    email: analytics@lists.wikimedia.org
    url: https://www.mediawiki.org/wiki/Analytics
  license:
    name: Apache licence, v2
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /:
    get:
      tags:
        - Media files data
      summary: List mediarequest API entry points.
      description: |
        This is the root of all media files data endpoints.  The list of paths that this returns includes ways to query by file, referer, top media files, etc.  If browsing the interactive documentation, see the specifics for each endpoint below.

        Stability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Stable)
      produces:
        - application/json
      responses:
        '200':
          description: The queriable sub-items
          schema:
            $ref: '#/definitions/listing'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-monitor: false

  /per-file/{referer}/{agent}/{file_path}/{granularity}/{start}/{end}:
    get:
      tags:
        - Mediarequests data
      summary: Get aggregated mediarequest counts for a media file.
      description: |
        Given a file stored in upload.wikimedia.org (the file storage for all media in any wiki) and a date range, returns a daily timeseries of its request counts. The data can be filtered by agent type.
        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)
      produces:
        - application/json
      parameters:
        - name: referer
          in: path
          description: The place that the request was made from. Non Wikimedia projects appear aggreggated under the classification "external". It can be any Wikimedia project (e.g. de.wikipedia), "all-referers", "internal", "external", "search-engine", "unknown" or "none".
          type: string
          required: true
        - name: agent
          in: path
          description: If you want to filter by agent type, use one of user or spider. If you are interested in media requests regardless of agent type, use all-agents
          type: string
          enum: ['all-agents', 'user', 'spider']
          required: true
        - name: file_path
          in: path
          description: 'The upload.wikimedia.org (the file storage for all media in any wiki) path to the file. It also should be URI-encoded, so that non-URI-safe characters like %, / or ? are accepted. Example: %2Fwiktionary%2Fte%2F4%2F40%2Fpeacocks.JPG'
          type: string
          required: true
        - name: granularity
          in: path
          description: The time unit for the response data. As of today, supported values are daily and monthly
          type: string
          enum: ['daily', 'monthly']
          required: true
        - name: start
          in: path
          description: The date of the first day to include, in YYYYMMDD format
          type: string
          required: true
        - name: end
          in: path
          description: The date of the last day to include, in YYYYMMDD format
          type: string
          required: true
      responses:
        '200':
          description: The list of values
          schema:
            $ref: '#/definitions/file'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: /{domain}/sys/mediarequests/per-file/{referer}/{agent}/{file_path}/{granularity}/{start}/{end}
      x-monitor: true
      x-amples:
        - title: Get per file requests
          request:
            params:
              domain: wikimedia.org
              referer: en.wikipedia
              file_path: '%2Ftest.jpg'
              agent: all-agents
              granularity: daily
              start: 1970010100
              end: 1970010100
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              items:
                - referer: en.wikipedia
                  file_path: '/test.jpg'
                  agent: all-agents
                  granularity: daily
                  timestamp: 1970010100
                  requests: 0

  /aggregate/{referer}/{media_type}/{agent}/{granularity}/{start}/{end}:
    get:
      tags:
        - Mediarequests data
      summary: Get aggregated mediarequest counts per referer.
      description: |
        Given a date range, returns a timeseries of mediarequest counts. You can filter by referer, media types and/or agent type. You can choose between daily and monthly granularity.
        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)
      produces:
        - application/json
      parameters:
        - name: referer
          in: path
          description: The place that the request was made from. Non Wikimedia projects appear aggreggated under the classification "external". It can be any Wikimedia project (e.g. de.wikipedia), "all-referers", "internal", "external", "search-engine", "unknown" or "none".
          type: string
          required: true
        - name: media_type
          in: path
          description: The media type that each file belongs to. It can be "all-media-types", "image", "audio", "video", "document", or "other". 
          type: string
          required: true
        - name: agent
          in: path
          description: If you want to filter by agent type, use one of user or spider. If you are interested in media requests regardless of agent type, use all-agents
          type: string
          enum: ['all-agents', 'user', 'spider']
          required: true
        - name: granularity
          in: path
          description: The time unit for the response data. As of today, supported values are daily and monthly
          type: string
          enum: ['daily', 'monthly']
          required: true
        - name: start
          in: path
          description: The date of the first day to include, in YYYYMMDD format
          type: string
          required: true
        - name: end
          in: path
          description: The date of the last day to include, in YYYYMMDD format
          type: string
          required: true
      responses:
        '200':
          description: The list of values
          schema:
            $ref: '#/definitions/referer'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: /{domain}/sys/mediarequests/aggregate/{referer}/{media_type}/{agent}/{granularity}/{start}/{end}
      x-monitor: true
      x-amples:
        - title: Get aggregate mediarequests
          request:
            params:
              domain: wikimedia.org
              referer: en.wikipedia
              media_type: all-media-types
              agent: all-agents
              granularity: daily
              start: 1970010100
              end: 1970010100
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              items:
                - referer: en.wikipedia
                  media_type: all-media-types
                  agent: all-agents
                  granularity: daily
                  timestamp: 1970010100
                  requests: 0

  /top/{referer}/{media_type}/{year}/{month}/{day}:
    get:
      tags:
        - Mediarequests data
      summary: Get the most requested files for a referer.
      description: |
        Lists the 1000 most requested files for a given referer and timespan (month or day). You can filter by access method
        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)
      produces:
        - application/json
      parameters:
        - name: referer
          in: path
          description: The place that the request was made from. Non Wikimedia projects appear aggreggated under the classification "external". It can be any Wikimedia project (e.g. de.wikipedia), "all-referers", "internal", "external", "search-engine", "unknown" or "none".
          type: string
          required: true
        - name: media_type
          in: path
          description: The media type that each file belongs to. It can be "all-media-types", "image", "audio", "video", "document", or "other". 
          type: string
          required: true
        - name: year
          in: path
          description: The year of the date for which to retrieve top files, in YYYY format.
          type: string
          required: true
        - name: month
          in: path
          description: The month of the date for which to retrieve top files, in MM format. If you want to get the top files of a whole month, the day parameter should be all-days.
          type: string
          required: true
        - name: day
          in: path
          description: The day of the date for which to retrieve top files, in DD format.
          type: string
          required: true
      responses:
        '200':
          description: The list of top files in the project
          schema:
            $ref: '#/definitions/tops'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri:  /{domain}/sys/mediarequests/top/{referer}/{media_type}/{year}/{month}/{day}
      x-monitor: true
      x-amples:
        - title: Get top files by mediarequests
          request:
            params:
              domain: wikimedia.org
              referer: en.wikipedia
              media_type: all-media-types
              year: '1970'
              month: '01'
              day: '01'
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              items:
                - referer: en.wikipedia
                  media_type: all-media-types
                  year: '1970'
                  month: '01'
                  day: '01'
                  files:
                    - file_path: '-'
                      requests: 0
                      rank: 1

definitions:
  # A https://tools.ietf.org/html/draft-nottingham-http-problem
  problem:
    required:
      - type
    properties:
      type:
        type: string
      title:
        type: string
      detail:
        type: string
      instance:
        type: string

  listing:
    description: The result format for listings
    required:
      - items
    properties:
      items:
        type: array
        items:
          type: string

  file:
    properties:
      items:
        type: array
        items:
          properties:
            referer:
              type : string
            file_path:
              type: string
            agent:
              type: string
            granularity:
              type: string
            timestamp:
              type: string
            requests:
              type: integer
              format: int64

  referer:
    properties:
      items:
        type: array
        items:
          properties:
            referer:
              type : string
            media_type:
              type : string
            agent:
              type: string
            granularity:
              type: string
            timestamp:
              type: string
            requests:
              type: integer
              format: int64

  tops:
    properties:
      items:
        type: array
        items:
          properties:
            referer:
              type: string
            media-type:
              type : string
            year:
              type: string
            month:
              type: string
            day:
              type: string
            files:
              type: array
              items:
                properties:
                  rank:
                    type: integer
                    format: int32
                  file_path:
                    type: string
                  requests:
                    type: integer
                    format: int64