# Analytics Query Service config
aqs_project: &aqs_project
  x-modules:
    - path: projects/aqs_default.yaml
      options: &default_options
        table:
          backend: cassandra
          hosts: [localhost]
          keyspace: system
          username: cassandra
          password: cassandra
          defaultConsistency: one # or 'localQuorum' for production
          storage_groups:
            - name: default.group.local
              domains: /./
        druid:
          scheme: http
          host: druid1004.eqiad.wmnet
          port: 8082
          query_path: /druid/v2/
          datasources:
            mediawiki_history: mediawiki_history_reduced

# Swagger spec root.
spec: &spec_root
  title: "The Analytics Query Service root"
  # Ensure compatibility with RESTBase response headers.
  x-request-filters:
    - path: lib/response_header_filters.js
  paths:
    /{domain:analytics.wikimedia.org}: *aqs_project

# The main service setup. Each worker can offer one or more services.
services:
  - name: aqs
    module: hyperswitch
    conf:
      port: 7231
      spec: *spec_root
      salt: secret
      default_page_size: 125

logging:
  name: aqs
  level: info
  #streams:
  #- type: gelf
  #  host: <%= @logstash_host %>
  #  port: <%= @logstash_port %>

metrics:
  #type: txstatsd
  #host: localhost
  #port: 8125
  #batch: true
