swagger: '2.0'
info:
  version: '1.0.0-beta'
  title: Analytics Pagecounts API (legacy metric)
  description: Analytics Pagecounts API (legacy metric)
  contact:
    name: Analytics
    email: analytics@lists.wikimedia.org
    url: https://www.mediawiki.org/wiki/Analytics
  license:
    name: Apache licence, v2
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /aggregate/{project}/{access-site}/{granularity}/{start}/{end}:
    get:
      tags:
        - Pagecounts data (legacy)
      description: |
        Given a project and a date range, returns a timeseries of pagecounts. You can filter by access site (mobile or desktop) and you can choose between monthly, daily and hourly granularity as well.
        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)
      produces:
        - application/json
      parameters:
        - name: project
          in: path
          description: The name of any Wikimedia project formatted like {language code}.{project name}, for example en.wikipedia. You may pass en.wikipedia.org and the .org will be stripped off. For projects like commons without language codes, use commons.wikimedia.
          type: string
          required: true
        - name: access-site
          in: path
          description: If you want to filter by access site, use one of desktop-site or mobile-site. If you are interested in pagecounts regardless of access site use all-sites.
          type: string
          enum: ['all-sites', 'desktop-site', 'mobile-site']
          required: true
        - name: granularity
          in: path
          description: The time unit for the response data. As of today, the supported granularities for this endpoint are hourly, daily and monthly.
          type: string
          enum: ['hourly', 'daily', 'monthly']
          required: true
        - name: start
          in: path
          description: The timestamp of the first hour/day/month to include, in YYYYMMDDHH format.
          type: string
          required: true
        - name: end
          in: path
          description: The timestamp of the last hour/day/month to include, in YYYYMMDDHH format. In hourly and daily granularities this value is inclusive, in the monthly granularity this value is exclusive.
          type: string
          required: true
      responses:
        '200':
          description: The list of values
          schema:
            $ref: '#/definitions/project'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              uri: /{domain}/sys/legacy/pagecounts/per-project/{project}/{access-site}/{granularity}/{start}/{end}
      x-monitor: false
      x-amples:
        - title: Get pagecounts
          request:
            params:
              domain: wikimedia.org
              project: en.wikipedia
              access-site: all-sites
              granularity: daily
              start: 1970010100
              end: 1970010100
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              items:
                - project: en.wikipedia
                  access-site: all-sites
                  granularity: daily
                  timestamp: 1970010100
                  count: 0
definitions:
  # A https://tools.ietf.org/html/draft-nottingham-http-problem
  problem:
    required:
      - type
    properties:
      type:
        type: string
      title:
        type: string
      detail:
        type: string
      instance:
        type: string

  listing:
    description: The result format for listings
    required:
      - items
    properties:
      items:
        type: array
        items:
          type: string

  project:
    properties:
      items:
        type: array
        items:
          properties:
            project:
              type : string
            access-site:
              type : string
            granularity:
              type: string
            timestamp:
              type: string
            count:
              type: integer
              format: int64
